// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVhyDnK_lgpypGis89VfCnn_UnQfnmgaI',
    appId: '1:559124015350:web:1526d11c58bbf4bcffe4d7',
    messagingSenderId: '559124015350',
    projectId: 'raikes-hacks',
    authDomain: 'raikes-hacks.firebaseapp.com',
    storageBucket: 'raikes-hacks.firebasestorage.app',
    measurementId: 'G-MPFNTTTPTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKhRqgVCTliJqg55viLsWyXvtFItgyrwQ',
    appId: '1:559124015350:android:dc033556305a375fffe4d7',
    messagingSenderId: '559124015350',
    projectId: 'raikes-hacks',
    storageBucket: 'raikes-hacks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNGHIsvu83fPusTbmBaAMfRqpHuSCQFQQ',
    appId: '1:559124015350:ios:47fd201b6548472fffe4d7',
    messagingSenderId: '559124015350',
    projectId: 'raikes-hacks',
    storageBucket: 'raikes-hacks.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNGHIsvu83fPusTbmBaAMfRqpHuSCQFQQ',
    appId: '1:559124015350:ios:47fd201b6548472fffe4d7',
    messagingSenderId: '559124015350',
    projectId: 'raikes-hacks',
    storageBucket: 'raikes-hacks.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVhyDnK_lgpypGis89VfCnn_UnQfnmgaI',
    appId: '1:559124015350:web:b57f2d153f780c9bffe4d7',
    messagingSenderId: '559124015350',
    projectId: 'raikes-hacks',
    authDomain: 'raikes-hacks.firebaseapp.com',
    storageBucket: 'raikes-hacks.firebasestorage.app',
    measurementId: 'G-PLM0D1FCJ1',
  );
}
